### ISSUE TITLE
https://gtagmodding.com/maps/gta5/ is down... 

### ISSUE THREAD

**Issue by koendebock** [oldnapalm/CoordRecorder#1]
Do you happen to know an alternative?

**Comment by oldnapalm** [comment]
Unfortunately the alternatives I found don't have an option to add your own markers.

The current version of the mod shows blips for the checkpoints in the game map though.

**Comment by oldnapalm** [comment]
You may want to try this script to create a course from a fit file

https://gist.github.com/oldnapalm/89ad17d0768f86197f85ed6a1cfae0ae

Ride using the tester version, save the activity and run the script

`python fit2json.py -i GTBikeV_xxxx.fit`

Requires https://www.python.org/ and https://pypi.org/project/fitdecode/ (`pip install fitdecode`)

**Comment by oldnapalm** [comment]
Found an alternative (https://mapgenie.io/), csv_to_course will now create an html file instead of copying the data to clipboard.

**Comment by koendebock** [comment]
Thanks!
